# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
    tags:
      - "v*.*.*"
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2022

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Enable Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64
          toolset: 14.30
          sdk: 10.0.22000.0

      - name: Generate version information
        run: powershell "${env:GITHUB_WORKSPACE}\Version.ps1" -ref "${{github.ref}}" -sha "${{github.sha}}"

      - name: Build
        run: msbuild.exe "${env:GITHUB_WORKSPACE}\GW2Radial.sln" /t:Build /p:Configuration=Release /p:Platform=x64 /p:GitHubDefs=USE_GITHUB_VER

      - name: Save nightly build from master
        uses: actions/upload-artifact@v2
        if: startsWith(github.ref, 'refs/tags/v') == false
        with:
          name: nightly-${{ github.sha }}
          path: |
            x64/Release/gw2addon_gw2radial_d3d9.dll
            x64/Release/readme.md
      - name: Move files for tag
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          mkdir -p x64/Release/gw2radial_d3d9
          mv x64/Release/gw2addon_gw2radial_d3d9.dll x64/Release/gw2radial_d3d9/
          mv x64/Release/readme.md x64/Release/gw2radial_d3d9/
      - name: Zip files for tag
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          cd x64/Release
          7z a ../../gw2radial_d3d9.zip gw2radial_d3d9/
          cd ../..
      - name: Create release draft for tag
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          body_path: CHANGELOG.md
          draft: true
          prerelease: ${{ contains(github.ref, '-pre') }}
          files: gw2radial_d3d9.zip

